version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: betnad-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: betnad
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - betnad-network

volumes:
  mongodb_data:

networks:
  betnad-network:
    driver: bridge
